import { OnStart } from "../../../node_modules/@easy-games/flamework-core";
import { Signal } from "../../Shared/Util/Signal";
import { AuthController } from "./Auth/AuthController";
import { MainMenuPageType } from "./MainMenuPageName";
export declare class MainMenuController implements OnStart {
    private readonly authController;
    private readonly socialTweenDuration;
    mainMenuGo: GameObject;
    refs: GameObjectReferences;
    currentPage: GameObject | undefined;
    currentPageType: MainMenuPageType;
    OnCurrentPageChanged: Signal<[page: MainMenuPageType, oldPage: MainMenuPageType | undefined]>;
    private pageMap;
    private wrapperRect;
    mainContentCanvas: Canvas;
    mainContentGroup: CanvasGroup;
    socialMenuGroup: CanvasGroup;
    private rootCanvasGroup;
    private toggleSocialButton;
    private open;
    private socialIsVisible;
    private avatarScene?;
    constructor(authController: AuthController);
    OpenFromGame(): void;
    CloseFromGame(): void;
    IsOpen(): boolean;
    OnStart(): void;
    RouteToPage(pageType: MainMenuPageType, force?: boolean, noTween?: boolean): void;
    private ToggleSocialView;
}
