import { OnStart } from "../../../Shared/Flamework";
import { CharacterInventorySingleton } from "../../../Shared/Inventory/CharacterInventorySingleton";
import { InventorySingleton } from "../../../Shared/Inventory/InventorySingleton";
import { CoreUIController } from "../UI/CoreUIController";
export declare class InventoryUIController implements OnStart {
    private readonly invController;
    private readonly characterInvController;
    private readonly coreUIController;
    private hotbarSlots;
    private backpackShown;
    private hotbarCanvas;
    private hotbarContent;
    private healthBar;
    private inventoryRefs;
    private backpackRefs;
    private backpackCanvas;
    private slotToBackpackTileMap;
    private enabled;
    private visible;
    private draggingState;
    private draggingBin;
    private spriteCacheForItemType;
    private firstSpawn;
    constructor(invController: InventorySingleton, characterInvController: CharacterInventorySingleton, coreUIController: CoreUIController);
    OnStart(): void;
    SetEnabled(enabled: boolean): void;
    private SetVisible;
    SetHealtbarVisible(visible: boolean): void;
    SetHotbarVisible(visible: boolean): void;
    OpenBackpack(): void;
    private SetupHotbar;
    private UpdateTile;
    private prevHeldSlot;
    private UpdateHotbarSlot;
    private SetupBackpack;
    IsBackpackShown(): boolean;
}
