import { Entity, EntityReferences } from "../../../Shared/Entity/Entity";
import { CameraReferences } from "./CameraReferences";
export declare class FirstPersonCameraSystem {
    readonly entity: Entity;
    private bobLerpMod;
    cameras: CameraReferences;
    private sprintingBob;
    private walkingBob;
    private slidingBob;
    private targetBobData;
    private currentBobData;
    private targetBobStrength;
    private currentBobStrength;
    private manualSpineOffset;
    private calculatedSpineOffset;
    private entityReferences;
    private cameraVars;
    private trackedHeadRotation;
    private inFirstPerson;
    private bin;
    private originalSpineMiddlePosition;
    private originalSpineTopPosition;
    private originalShoulderLPosition;
    private originalShoulderRPosition;
    private currentTime;
    private viewmodelController;
    constructor(entity: Entity, entityReferences: EntityReferences, startInFirstPerson: boolean);
    Destroy(): void;
    private LateUpdate;
    OnMovementStateChange(state: EntityState): void;
    OnFirstPersonChanged(isFirstPerson: boolean): void;
}
