import { MainMenuController } from "../MainMenuController";
import MainMenuPageComponent from "../MainMenuPageComponent";
import { MainMenuPageType } from "../MainMenuPageName";
export default class AvatarMenuComponent extends MainMenuPageComponent {
    private readonly generalHookupKey;
    private readonly tweenDuration;
    private readonly highlightColor;
    private readonly normalColor;
    private subNavBarBtns;
    private mainNavBtns?;
    private subNavBars?;
    private outfitBtns?;
    private activeMainIndex;
    private activeSubIndex;
    itemButtonHolder?: Transform;
    itemButtonTemplate?: GameObject;
    avatarRenderHolder?: GameObject;
    categoryLabelTxt?: TextMeshProUGUI;
    private currentSlot;
    private outfits?;
    private currentUserOutfit?;
    private currentUserOutfitIndex;
    private clientId;
    private Log;
    Init(mainMenu: MainMenuController, pageType: MainMenuPageType): void;
    OpenPage(): void;
    ClosePage(instant?: boolean): void;
    private SelectMainNav;
    private SelectSubNav;
    private DisplayItemsOfType;
    private DisplayItems;
    private itemButtonBin;
    private ClearItembuttons;
    private DisplayColorScheme;
    private DisplaySkinTextures;
    private AddColorButton;
    private AddItemButton;
    private SelectItem;
    private SelectSkinItem;
    private SelectSkinColor;
    private OnSelectClear;
    private OnSelectCurrent;
    private OnDragAvatar;
    private InitializeAutherizedAccessories;
    private LoadAllOutfits;
    private SelectOutfit;
    private LoadCurrentOutfit;
    private Save;
    private Revert;
    private SetButtonColor;
}
