import { MainMenuController } from "../MainMenuController";
import MainMenuPageComponent from "../MainMenuPageComponent";
import { MainMenuPageType } from "../MainMenuPageName";
export default class AvatarMenuComponent extends MainMenuPageComponent {
    private readonly GeneralHookupKey;
    private readonly TweenDuration;
    private subNavBarBtns;
    private mainNavBtns?;
    private subNavBars?;
    private activeMainIndex;
    private activeSubIndex;
    ItemButtonHolder?: Transform;
    ItemButtonTemplate?: GameObject;
    private currentSlot;
    private Log;
    Init(mainMenu: MainMenuController, pageType: MainMenuPageType): void;
    OpenPage(): void;
    ClosePage(instant?: boolean): void;
    private SelectMainNav;
    private SelectSubNav;
    private DisplayItemsOfType;
    private DisplayItems;
    private itemButtonBin;
    private ClearItembuttons;
    private DisplayColorScheme;
    private DisplaySkinTextures;
    private AddColorButton;
    private AddItemButton;
    private SelectItem;
    private SelectSkinItem;
    private SelectSkinColor;
    private OnSelectClear;
    private OnSelectCurrent;
    private OnDragAvatar;
}
