import { DirectMessageController } from "../../MainMenuControllers/Social/DirectMessages/DirectMessageController";
import { FriendsController } from "../../MainMenuControllers/Social/FriendsController";
import { SocketController } from "../../MainMenuControllers/Socket/SocketController";
import { ChatCommand } from "../../../Shared/Commands/ChatCommand";
import { OnStart } from "../../../Shared/Flamework";
import { Player } from "../../../Shared/Player/Player";
import { LocalCharacterSingleton } from "../../../Shared/Character/LocalCharacter/LocalCharacterSingleton";
import { CoreUIController } from "../UI/CoreUIController";
export declare class ChatController implements OnStart {
    private readonly localEntityController;
    private readonly coreUIController;
    private readonly socketController;
    private readonly directMessageController;
    private readonly friendsController;
    private canvas;
    private content;
    private wrapper;
    private chatMessagePrefab;
    private inputField;
    private inputWrapperImage;
    private selected;
    private selectedBin;
    private chatMessageElements;
    private prevSentMessages;
    private historyIndex;
    private commands;
    private lastChatMessageRenderedTime;
    constructor(localEntityController: LocalCharacterSingleton, coreUIController: CoreUIController, socketController: SocketController, directMessageController: DirectMessageController, friendsController: FriendsController);
    OpenMobile(): void;
    HideMobile(): void;
    IsOpenMobile(): boolean;
    RegisterCommand(command: ChatCommand): void;
    IsOpen(): boolean;
    OnStart(): void;
    private CheckIfShouldHide;
    ShowAllChatMessages(): void;
    SubmitInputField(): void;
    SendChatMessage(message: string): void;
    RenderChatMessage(message: string, sender?: Player): void;
    ClearChatMessages(): void;
    IsChatFocused(): boolean;
}
