export const enum Layer {
	DEFAULT = 0,
	TRANSPARENT_FX = 1,
	IGNORE_RAYCAST = 2,
	CHARACTER = 3,
	BLOCK = 6,
	BRIDGE_ASSIST = 7,
	IGNORE_COLLIDE = 8,
	GROUND_ITEM = 9,
	FIRST_PERSON = 10,
	PROJECTILE = 11,
	GENERATOR_ITEM = 12,
}
